ecommerce/planthouse/cart/urls.py
from django.urls import path
from .import views

app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('', views.cart_details, name="cart_details"),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('trash/<int:product_id>/',views.full_remove,name='trash')

]

ecommerce/planthouse/planthouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plantproducts/',include('plantproducts.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/planthouse/plantproducts/urls.py
from . import views
from django.urls import path, include
app_name='plantproducts'
urlpatterns=[
    path('',views.allcategory,name='AllProdC'),
    path('<slug:c_slug>/',views.allcategory,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodcategory,name="ProdCat")

]

ecommerce/planthouse/search/urls.py
from django.urls import path
from .import views

app_name='search'
urlpatterns=[
    path('',views.Search,name="Searchtext")
]

ecommerce/planthouse/cart/models.py
from django.db import models
from plantproducts.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date']
    def __str__(self):
        return '{}'.format (self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    def total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format (self.product)

ecommerce/planthouse/plantproducts/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='plant',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
         return '{}'.format(self.name)

    def get_url(self):
        return reverse('plantproducts:products_by_category',args=[self.slug])

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='plant',blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return  '{}'.format(self.name)

    def get_url(self):
        return reverse('plantproducts:ProdCat',args=[self.category.slug,self.slug])

ecommerce/planthouse/search/models.py
from django.db import models

# Create your models here.

ecommerce/planthouse/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart,CartItem
from plantproducts.models import Product
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
          cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
    return redirect('cart:cart_details')

def cart_details(request,total=0,counter=0,cart_items=None):
    try:
       cart=Cart.objects.get(cart_id=cart_id(request))
       cart_items=CartItem.objects.filter(cart=cart,active=True)
       for cart_item in cart_items:
           total+=(cart_item.product.price * cart_item.quantity)
           counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    products=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=products,cart=cart)
    if cart_item.quantity >= 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    products=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=products,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

ecommerce/planthouse/plantproducts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
# def index(request):
#     return HttpResponse("hello")

def allcategory(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,5)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"categories.html",{'category':c_page,'products':products})

def prodcategory(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce/planthouse/search/views.py
from django.shortcuts import render
from plantproducts.models import Product
from django.db.models import Q
# Create your views here.

def Search(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerce/planthouse/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title> {% block title %} {% endblock %}</title>
</head>
<body style="font-family: 'Roboto', sans-serif;" >
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerce/planthouse/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Wide variety of products
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center my_title">Your Shopping Cart is Empty</h1><br>
        <p class="text-center">Please Click <a href="{% url 'plantproducts:AllProdC' %}">Here</a>To Continue Purchase.</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center"><br>
        <h3 class="text-center my_title">
            Your Shopping Cart
        </h3><br>
    </div>
    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                <thead class="table_head">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody>
                      {% for cart_item in cart_items %}
                 <tr>
                     <td>
                   <a href=""><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" style="width:100px; height:100px;"></a>
                     </td>
                     <td class="text-left">
                         {{cart_item.product.name}}
                         <br>
                         SKU: {{cart_item.product.id}}
                         <br>
                         Price: $ {{cart_item.product.price}}
                         <br>
                         Qty: {{cart_item.quantity}} x $ {{cart_item}}
                     </td>
                     <td>
                         $ {{cart_item.total}}
                     </td>
                     {% if cart_item.quantity < cart_item.product.stock %}
                     <td>
                         <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                         &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                         &nbsp;&nbsp;<a href="{% url 'cart:trash' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                     </td>
                     {% else %}
                     <td>
                     &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_a"><i class=" fa fa-minus custom_icon"></i></a>
                     &nbsp;&nbsp;<a href="{% url 'cart:trash' cart_item.product.id %}" class="custom_a"><i class=" fa fa-trash custom_icon"></i></a>
                     </td>
                     {% endif %}
                 </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class=" table my_table">
                    <thead class="table_head">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <b>Please Review Your Cart Before Checkout...</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Your Total Price Is <strong>{{total}}</strong>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div class="mx_auto">
                    <a href="{% url 'plantproducts:AllProdC' %}" class="btn btn-secondary btn-block my_custom_button">Continue</a>
                </div>
                {% endif %}
                <table class=" table my_table">
                    <thead class="table_head">
                    <tr>
                        <th>
                            Payment
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <br><b>Please Do Payment Procedure If Confirmed</b>
                        </td>
                    </tr>
                    <br>
                    </tbody>
                </table>
                <div>
                    <img src="{% static 'image/google.png' %}" height="100px;" width="100px;">&nbsp;
                    <img src="{% static 'image/mastercard.png' %}"  height="50px;" width="50px;">&nbsp;
                    <img src="{% static 'image/paypal.png' %}"  height="50px;" width="50px;">&nbsp;
                    <img src="{% static 'image/download.png' %}"  height="70px;" width="70px;">
                </div>
                <div class="mx_auto">
                    <a href="{% url 'plantproducts:AllProdC' %}" class="btn btn-secondary btn-block my_custom_button">Pay</a>
                </div>
            </div>
        </div>
    </div><br><br><br><br><br>

{% endblock %}

ecommerce/planthouse/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155}}
   {% else %}
       welcome to our webiste
    {% endif %}
{% endblock %}

{% block title %}
   {% if category %}
     {{category.name}}-Plant House
   {% else %}
     Plant House
   {% endif %}
{% endblock %}

{% block content %}
  {% if category %}
     <div>
        <div class="row my_row_class">
            <div class="mx-auto">
           <p>
              <a href="{% url 'plantproducts:AllProdC' %}">Our Produts</a>
           </p>
        </div>
            </div>
     </div>
  {% endif %}
<div class="mx-auto">
   {% if category %}
     <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center  my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
 {% else %}
<div>
   <img class="my_image my_image_padding" src="{% static 'image/PLANT HOUSE.png' %}" alt="our products">
</div>
<br>
<div>
    <h1 class="text-center my_title">Our Product Collections</h1>
    <p class="text-justify">Indoor plants should be an essential component of every interior design. Greenery brightens up indoor spaces and is known to have mood-boosting qualities.Indoor plants are popular because they are relatively easy to take care of, provide health benefits and can be used in a variety of indoor décor themes. Indoor plants are a great option for those who have little yard space for an outdoor garden or for those who live in climates with severely cold winters.</p>
    <p class="text-justify">Plants that need low maintenance and grow up easily on the outside are known as Outdoor plants. Outdoor plants give us oxygen and absorb carbon dioxide during the photosynthesis process, but also reduce stress, anxiety, and tiredness and give us relaxation. Outside plants have different categories such as include trees, shrubs, non-flowering plants, and flowering plants.</p>
</div>
{% endif %}
<div class="container">
   <div class="row mx_auto">
      {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
            <div class="card">
            <div class="card text-center" style="min-width:18rem;">
              <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:340px; height:250px;">
              </a>
           </div>
           <div class="card-body">
              <h4>{{product.name}}</h4>
              <p>{{product.price}}</p>
           </div>
            </div>
        </div>
       {% endfor %}
   </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
           <div class="text-center">
              {% for pg in products.paginator.page_range %}
                   <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == page %} active {% endif %} ">{{pg}}</a>
              {% endfor %}
            </div>
         {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce/planthouse/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Plant House. All Right Reserved </p>
</div>

ecommerce/planthouse/templates/header.html
{% load static %}
<header>
    <center>
    <a href="{% url 'plantproducts:AllProdC' %}"><img src="{% static 'image/logo.jpg' %}" alt="logo image" width="180px;" height="180px;">
    </center>
</header>

ecommerce/planthouse/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'plantproducts:AllProdC' %}">Products</a>
        </li>
        <li class="nav-item dropdown {% if 'plantproducts' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'plantproducts:AllProdC' %}">All Products</a></li>
                     {% for cart in links %}
            <li><a class="dropdown-item" href="{{cart.get_url}}">{{cart.name}}</a></li>
                     {% endfor %}
         </ul>
        </li>
           {% if item_count > 0 %}
              <li class="nav-item">
                 <a class="nav-link" href="{% url 'cart:cart_details' %}"><i class="fa fa-shopping-cart">({{item_count}})</i></a>
              </li>
           {% endif %}
         </ul>
          <form class="d-flex" method="get" action="{% url 'search:Searchtext' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/planthouse/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description | truncatewords:155 }}
{% endblock %}

{% block title %}
{% if category %}
   {{product.name}}
 {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'plantproducts:AllProdC' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:300px; height:300px;">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"><b>{{product.name}}</b></h1>
                  <p>${{product.price}}</p>
                  <p  class="my_title"><b>Product Description</b></p>
                  <p style="font-family:Goudy-old-style" class="text-justify my_prod_text">{{product.description}}</p>
                   {% if product.stock <= 0 %}
                       <p class="tetx-justify my_prod_text"><b>Out of Stock</b></p>
                   {% else %}
                   <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
                   {% endif %}
             </div>
        </div>
    </div>
</div> <br><br><br><br><br>

{% endblock %}

ecommerce/planthouse/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Wide variety of products
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div class="text-center my_text_search">You have searched for: <b>"{{query}}"</b></div>

<div class="container">
   <div class="row mx_auto">
      {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
            <div class="card">
            <div class="card text-center" style="min-width:18rem;">
              <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:340px; height:250px;">
              </a>
           </div>
           <div class="card-body">
              <h4>{{product.name}}</h4>
              <p>{{product.price}}</p>
           </div>
            </div>
        </div>

       {% empty %}
         <div class="row mx-auto">
             <p class="text-center my_text_search">0 Results Found
         </p>
         </div>
        {% endfor %}
   </div>
</div><br><br><br><br><br>
{% endblock %}